name: ✨ Feature
description: Request a new feature or propose an improvement.
title: "[Feat]: "
type: "feature"
body:
  - type: textarea
    attributes:
      label: My suggestion
      description: Describe the changes you're suggesting and how they work.
      placeholder: Add an option to...
    validations:
      required: true

  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
        - label: Could this feature be implemented as a module?
